Repository YAPP-Github/23rd-Web-Team-2-FE, pull requests merged in 2024-02, with the labels that each got.

#50 [Feature/BAR-230] github checkout version up
  .github/workflows/deploy.yaml
Labels: feature

#48 [Feature/BAR-145] 로그인 구현
  .env.local
  .env.production
  .storybook/main.ts
  .storybook/preview.ts
  middleware.ts
  package.json
  pages/intro/index.tsx
  pnpm-lock.yaml
  src/api/auth/auth.ts
  src/api/auth/types/index.ts
  src/api/http.ts
  src/components/Layout/components/Header.tsx
  src/components/Layout/components/LoginButton.tsx
  src/components/Layout/components/ProfileButton.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/components/Modal/modals/Login.tsx
  src/constants/routes.ts
  src/models/layout.ts
  src/queries/auth.ts
  src/queries/useSpellCheck.ts
  src/stores/token.ts
  tsconfig.json
Labels: feature

#51 [Feature/ BAR-225] 맞춤법 검사 결과 카드 UI 구현
  pages/api/spell-check.ts
  src/api/spell/types/index.ts
  src/assets/icons/bookmark.svg
  src/assets/icons/complete.svg
  src/assets/icons/copy.svg
  src/assets/icons/menu.svg
  src/assets/icons/pencil-active.svg
  src/assets/icons/pencil-default.svg
  src/assets/icons/spelling.svg
  src/assets/icons/template-active.svg
  src/assets/icons/template-default.svg
  src/components/Button/style.css.ts
  src/components/Card/style.css.ts
  src/components/Icon/index.tsx
  src/components/Layout/style.css.ts
  src/components/Loading/Skeleton/SkeletonContent/index.tsx
  src/components/Tabs/components/TabsTrigger.tsx
  src/constants/icon.ts
  src/constants/spellCheck.ts
  src/domain/Write/Today/components/Card/index.tsx
  src/domain/Write/Today/components/Card/style.css.ts
  src/domain/Write/Today/components/SpellCheckCard/index.tsx
  src/domain/Write/Today/components/SpellCheckCard/style.css.ts
  src/domain/Write/Today/components/SpellCheckNotice/index.tsx
  src/domain/Write/Today/components/SpellCheckNotice/style.css.ts
  src/domain/Write/Today/components/SpellTypeBox/index.tsx
  src/domain/Write/Today/components/SpellTypeBox/style.css.ts
  src/queries/useSpellCheck.ts
  tsconfig.json
  types/entries.d.ts
Labels: feature

#49 [Feature/BAR-149] 참고하는 페이지 UI 구성
  middleware.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/intro/index.tsx
  pages/main/index.tsx
  src/assets/icons/arrowDown.svg
  src/assets/icons/bookmarkRefer.svg
  src/components/Button/style.css.ts
  src/components/Card/index.tsx
  src/components/Card/style.css.ts
  src/components/Layout/MainPageTab.tsx
  src/components/Layout/components/Footer.tsx
  src/components/Layout/components/Header.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/style.css.ts
  src/constants/icon.ts
  src/constants/routes.ts
  src/domain/Write/components/WritePageTab.tsx
  src/domain/Write/components/style.css.ts
  src/domain/참고하는/components/FilterHeader.css.ts
  src/domain/참고하는/components/FilterHeader.tsx
  src/domain/참고하는/components/ReferTab.css.ts
  src/domain/참고하는/components/index.tsx
  src/domain/참고하는/components/참고하는TemplateCard.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/domain/참고하는/models/index.ts
  src/domain/참고하는/types/index.ts
  src/domain/참고하는/utils/index.ts
  src/styles/global.css.ts
  src/styles/sprinkles.css.ts
Labels: feature

#55 [Fix/BAR-232] 페이지 전환시 CSS 파일이 생성되지 않는 문제 해결
  package.json
  pnpm-lock.yaml
Labels: fix

#52 [Feature/BAR-147] 로그인/토큰 리프레시 구현
  middleware.ts
  package.json
  pages/redirect/[authType]/index.tsx
  pnpm-lock.yaml
  src/api/auth/auth.ts
  src/api/http.ts
  src/stores/token.ts
  src/utils/token.ts
Labels: feature

#58 [Refactor/BAR-233] Dropdown 컴포넌트 수정
  .storybook/preview-body.html
  src/assets/icons/profileDialog.svg
  src/assets/icons/profileHeader.svg
  src/components/Card/index.tsx
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/components/DialogButton.tsx
  src/components/Dialog/components/DialogTitle.tsx
  src/components/Dialog/index.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/components/DropdownItem.tsx
  src/components/Dropdown/components/DropdownList.tsx
  src/components/Dropdown/components/DropdownTitle.tsx
  src/components/Dropdown/components/DropdownTrigger.tsx
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.css.ts
  src/components/Layout/MainPageTab.tsx
  src/components/Layout/components/Header.tsx
  src/components/Layout/components/LoginButton.tsx
  src/components/Layout/components/ProfileButton.tsx
  src/components/Layout/components/ProfileDialog.tsx
  src/components/Layout/components/UserButton.tsx
  src/components/Layout/style.css.ts
  src/components/Tabs/components/TabsContent.tsx
  src/components/Tabs/components/TabsList.tsx
  src/components/Tabs/components/TabsTrigger.tsx
  src/components/Tabs/index.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/components/TooltipContent.tsx
  src/components/Tooltip/components/TooltipTrigger.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/style.css.ts
  src/constants/portal.ts
  src/constants/routes.ts
  src/hooks/useClickAway.ts
  src/hooks/useDialogContext.ts
  src/hooks/useDisclosure.ts
  src/hooks/usePosition.ts
  src/hooks/useTabsContext.ts
  src/hooks/useTooltipContext.ts
  src/utils/getPosition.ts
Labels: refactor

#53 [Feature/BAR-169] 끄적이는 페이지 개발
  pages/main/index.tsx
  src/assets/icons/clock-active.svg
  src/assets/icons/clock.svg
  src/components/AsyncBoundary/components/ErrorBoundary.tsx
  src/components/AsyncBoundary/components/ErrorScreen.tsx
  src/components/AsyncBoundary/index.tsx
  src/components/Card/index.tsx
  src/components/Input/WriteInput/index.tsx
  src/components/Input/WriteInput/style.css.ts
  src/components/Layout/style.css.ts
  src/components/Providers/TanstackQueryProvider.tsx
  src/constants/icon.ts
  src/domain/Write/History/components/Card/index.tsx
  src/domain/Write/History/index.tsx
  src/domain/Write/types/index.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/History/style.css.ts
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Card/Today/style.css.ts
  src/domain/끄적이는/components/Card/components/BookMarkDialog.tsx
  src/domain/끄적이는/components/Card/components/SettingDialog.tsx
  src/domain/끄적이는/components/Card/components/setting.css.ts
  src/domain/끄적이는/components/Guide/index.tsx
  src/domain/끄적이는/components/Guide/style.css.ts
  src/domain/끄적이는/components/History/Column/index.tsx
  src/domain/끄적이는/components/History/Column/style.css.ts
  src/domain/끄적이는/components/History/index.css.ts
  src/domain/끄적이는/components/History/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckCard/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckCard/style.css.ts
  src/domain/끄적이는/components/Today/components/SpellCheckNotice/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckNotice/style.css.ts
  src/domain/끄적이는/components/Today/components/SpellTypeBox/index.tsx
  src/domain/끄적이는/components/Today/components/SpellTypeBox/style.css.ts
  src/domain/끄적이는/components/Today/index.css.ts
  src/domain/끄적이는/components/Today/index.tsx
  src/domain/끄적이는/constants/queryKeys.ts
  src/domain/끄적이는/mutations/useCreateTemporalMemo.ts
  src/domain/끄적이는/mutations/useDeleteTemporalMemo.ts
  src/domain/끄적이는/mutations/useEditTemporalMemo.ts
  src/domain/끄적이는/queries/useGetHistory.ts
  src/domain/끄적이는/style.css.ts
  src/domain/끄적이는/types/index.ts
  src/hooks/useModal.ts
Labels: feature

#54 [Feature/BAR-175] 계정설정 페이지 구현
  pages/index.tsx
  pages/main/index.tsx
  pages/profile/index.tsx
  src/assets/icons/Google2.svg
  src/assets/icons/Kakao2.svg
  src/assets/icons/Naver2.svg
  src/assets/icons/check-box-active.svg
  src/assets/icons/check-box.svg
  src/assets/icons/close-active.svg
  src/assets/icons/error.svg
  src/assets/icons/picture.svg
  src/components/Icon/index.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/constants/icon.ts
  src/domain/계정설정/components/ExitModal/components/ListItem.tsx
  src/domain/계정설정/components/ExitModal/components/style.css.ts
  src/domain/계정설정/components/ExitModal/index.tsx
  src/domain/계정설정/components/ExitModal/style.css.ts
  src/domain/계정설정/components/Form/components/Input/index.css.ts
  src/domain/계정설정/components/Form/components/Input/index.tsx
  src/domain/계정설정/components/Form/index.css.ts
  src/domain/계정설정/components/Form/index.tsx
  src/domain/계정설정/constants/index.ts
  src/domain/계정설정/constants/queryKeys.ts
  src/domain/계정설정/index.css.ts
  src/domain/계정설정/mutations/useExitAccount.ts
  src/domain/계정설정/mutations/useUpdateProfile.ts
  src/domain/계정설정/mutations/useUpdateProfileImage.ts
  src/domain/계정설정/queries/useGetProfile.ts
  src/domain/계정설정/types/index.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/hooks/useInput.ts
Labels: feature

#59 [Feature/BAR-146] 헤더, 푸터 링크 및 기능 처리
  middleware.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/main/index.tsx
  pages/profile/index.tsx
  pages/redirect/[authType]/index.tsx
  pages/terms/privacy/index.tsx
  pages/terms/use/index.tsx
  pnpm-lock.yaml
  src/api/http.ts
  src/api/members/index.ts
  src/api/members/types/index.ts
  src/components/Input/WriteInput/index.tsx
  src/components/Layout/components/Footer.tsx
  src/components/Layout/components/Header.tsx
  src/components/Layout/components/ProfileButton.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/components/Modal/components/ModalContainer.tsx
  src/components/Modal/modals/Login.tsx
  src/constants/routes.ts
  src/queries/useGetMyProfile.ts
  src/queries/useLogin.ts
Labels: feature

#56 [Feature/BAR-150] 참고하는 메인 필터, 서브 필터 UI 개발
  pages/profile/index.tsx
  pages/redirect/[authType]/index.tsx
  src/api/auth/index.ts
  src/api/http.ts
  src/api/memoFolder/index.ts
  src/api/memoFolder/types/index.ts
  src/api/spell/index.ts
  src/assets/icons/arrowDown.svg
  src/assets/icons/arrowUp.svg
  src/assets/icons/ask.svg
  src/assets/icons/celebrate.svg
  src/assets/icons/comfort.svg
  src/assets/icons/regard.svg
  src/assets/icons/report.svg
  src/assets/icons/thank.svg
  src/components/Button/index.tsx
  src/components/Dropdown/components/DropdownItem.tsx
  src/components/Icon/index.tsx
  src/components/Layout/MainPageTab.tsx
  src/components/Layout/components/ProfileButton.tsx
  src/components/Layout/style.css.ts
  src/components/Modal/index.tsx
  src/components/Modal/modals/DeleteArticle.tsx
  src/components/Modal/modals/MakeFolder.tsx
  src/components/Modal/style.css.ts
  src/constants/icon.ts
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/참고하는/api/index.ts
  src/domain/참고하는/components/FilterButtons.css.ts
  src/domain/참고하는/components/FilterButtons.tsx
  src/domain/참고하는/components/FilterHeader.css.ts
  src/domain/참고하는/components/FilterHeader.tsx
  src/domain/참고하는/components/FolderDialog.css.ts
  src/domain/참고하는/components/FolderDialog.tsx
  src/domain/참고하는/components/HoverButton.tsx
  src/domain/참고하는/components/ReferTab.css.ts
  src/domain/참고하는/components/index.tsx
  src/domain/참고하는/components/참고하는TemplateCard.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/domain/참고하는/models/index.ts
  src/domain/참고하는/queries/useSaveTemplate.ts
  src/domain/참고하는/queries/useTemplates.ts
  src/domain/참고하는/types/index.ts
  src/queries/useGetMemoFolders.ts
  src/queries/useLogin.ts
  src/queries/usePostMemoFolders.ts
  src/queries/usePostSpellCheck.ts
  src/stores/modal.ts
  src/styles/global.css.ts
Labels: feature

#61 [Feature/BAR-169] 끄적이는 수정 모드 구현
  src/components/Card/style.css.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/History/style.css.ts
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Card/Today/style.css.ts
  src/domain/끄적이는/components/EditInput.tsx
  src/domain/끄적이는/components/History/Column/index.tsx
  src/domain/끄적이는/components/History/index.tsx
  src/domain/끄적이는/components/Today/index.tsx
  src/domain/끄적이는/components/editInput.css.ts
Labels: feature

#63 [Feature/BAR-155] 참고하는 레이아웃 수정 및 폴더 저장 삭제 기능 추가
  package.json
  pnpm-lock.yaml
  src/components/Card/style.css.ts
  src/components/Responsive/index.tsx
  src/domain/참고하는/api/index.ts
  src/domain/참고하는/components/FolderDialog.css.ts
  src/domain/참고하는/components/FolderDialog.tsx
  src/domain/참고하는/components/index.tsx
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/domain/참고하는/queries/useCopyTemplate.ts
  src/domain/참고하는/queries/useDeleteTemplate.ts
  src/domain/참고하는/queries/useSaveTemplate.ts
  src/domain/참고하는/types/index.ts
  src/styles/sprinkles.css.ts
Labels: feature

#64 [Feature/BAR-231] 저장하는 페이지 UI 구현
  pages/_app.tsx
  pages/archive/index.tsx
  src/assets/images/empty.svg
  src/components/Card/Card.stories.tsx
  src/components/Card/style.css.ts
  src/components/Column/index.tsx
  src/components/Column/style.css.ts
  src/components/Dropdown/MenuDropdown/index.tsx
  src/components/Layout/components/UserButton.tsx
  src/components/Layout/style.css.ts
  src/components/Loading/Spinner/index.tsx
  src/components/Loading/Spinner/style.css.ts
  src/components/Tabs/components/TabsContent.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/style.css.ts
  src/constants/config.ts
  src/constants/routes.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Card/components/BookMarkDialog.tsx
  src/domain/끄적이는/components/Card/components/SettingDialog.tsx
  src/domain/끄적이는/components/Card/components/setting.css.ts
  src/domain/저장하는/api/index.ts
  src/domain/저장하는/components/Archive/index.tsx
  src/domain/저장하는/components/Archive/style.css.ts
  src/domain/저장하는/components/ArchiveFolder/index.tsx
  src/domain/저장하는/components/ArchiveFolder/style.css.ts
  src/domain/저장하는/components/ArchiveTab/index.tsx
  src/domain/저장하는/components/ArchiveTabContent/index.tsx
  src/domain/저장하는/components/ArchiveTabContent/style.css.ts
  src/domain/저장하는/components/ArchivedCard/index.tsx
  src/domain/저장하는/components/ArchivedCard/style.css.ts
  src/domain/저장하는/components/NotFoundArchiveCard/index.tsx
  src/domain/저장하는/components/NotFoundArchiveCard/style.css.ts
  src/domain/저장하는/constants/queryKeys.ts
  src/domain/저장하는/mutations/useDeleteArchives.ts
  src/domain/저장하는/mutations/useUpdateArchives.ts
  src/domain/저장하는/queries/useGetArchives.ts
  src/domain/저장하는/types/index.ts
  src/styles/medias.css.ts
  src/utils/parserColumn.ts
Labels: feature

#65 [Fix/BAR-235] Dropdown 컴포넌트 위치 오류 해결
  .storybook/preview-body.html
  src/components/Dropdown/components/DropdownList.tsx
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.css.ts
  src/components/Layout/components/ProfileButton.tsx
  src/components/Tooltip/components/TooltipContent.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/style.css.ts
  src/constants/portal.ts
  src/hooks/usePosition.ts
Labels: fix

#66 [Feature/BAR-236] 저장하는 페이지 폴더 수정/삭제 기능 구현
  src/api/http.ts
  src/api/memoFolder/constants/queryKey.ts
  src/api/memoFolder/index.ts
  src/api/memoFolder/mutations/useDeleteMemoFolder.ts
  src/api/memoFolder/mutations/useUpdateMemoFolder.ts
  src/components/Button/style.css.ts
  src/components/Dropdown/style.css.ts
  src/components/Input/WriteInput/index.tsx
  src/components/Modal/components/ModalContainer.tsx
  src/components/Modal/components/ModalLayout.tsx
  src/components/Modal/index.tsx
  src/components/Modal/modals/EditFolder.tsx
  src/components/Modal/style.css.ts
  src/domain/저장하는/components/ArchiveFolder/index.tsx
  src/domain/저장하는/components/ArchiveFolder/style.css.ts
  src/domain/저장하는/components/DeleteFolderModal/index.tsx
  src/domain/저장하는/components/DeleteFolderModal/style.css.ts
  src/domain/저장하는/components/Folder/index.tsx
  src/domain/저장하는/components/Folder/style.css.ts
  src/domain/저장하는/components/NotFoundArchiveCard/index.tsx
  src/stores/modal.ts
Labels: feature

#68 [Feature/BAR-238] 최근 로그인 정보 반영
  pages/redirect/[authType]/index.tsx
  src/api/http.ts
  src/components/Layout/components/ProfileButton.tsx
  src/components/Layout/index.tsx
  src/components/Modal/modals/Login.tsx
  src/components/Modal/style.css.ts
  src/models/storage.ts
  src/utils/token.ts
Labels: feature

#71 [Feature/BAR-241] not found page 작성
  pages/404.tsx
  pages/redirect/[authType]/index.tsx
  src/assets/images/notFound.svg
  src/styles/notFound.css.ts
Labels: feature

#73 [Feature/BAR-243] 끄적이는 페이지 상단 탭 툴팁 노출 및 폴더 기능 추가
  pages/main/index.tsx
  src/components/Dropdown/FolderDropdown/index.tsx
  src/components/Dropdown/FolderDropdown/style.css.ts
  src/components/Dropdown/style.css.ts
  src/components/Layout/MainPageTab.tsx
  src/components/Responsive/index.tsx
  src/components/Tooltip/style.css.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/History/Column/index.tsx
  src/domain/끄적이는/components/History/Column/style.css.ts
  src/domain/끄적이는/components/History/index.css.ts
  src/domain/끄적이는/components/History/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckNotice/style.css.ts
  src/domain/끄적이는/components/Today/index.css.ts
  src/domain/끄적이는/components/Today/index.tsx
  src/domain/끄적이는/mutations/useSaveTemporalMemo.ts
  src/domain/끄적이는/style.css.ts
  src/domain/끄적이는/types/index.ts
  src/domain/저장하는/components/ArchiveFolder/index.tsx
  src/domain/저장하는/components/ArchiveFolder/style.css.ts
  src/domain/저장하는/components/ArchiveTabContent/index.tsx
  src/domain/저장하는/components/Folder/index.tsx
  src/domain/저장하는/components/Folder/style.css.ts
  src/domain/참고하는/components/FolderDialog.tsx
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/styles/global.css.ts
Labels: feature

#72 [Feature/BAR-242] head 태그 추가
  .github/workflows/deploy.yaml
  pages/_app.tsx
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
Labels: feature

#74 [Feature/BAR-245] 랜딩페이지 작성
  pages/index.tsx
  public/fonts/GmarketSansBold.otf
  public/fonts/GmarketSansLight.otf
  public/fonts/GmarketSansMedium.otf
  src/assets/icons/logo235.svg
  src/assets/icons/sadFace.svg
  src/assets/icons/smileFace.svg
  src/assets/images/fifthLanding.png
  src/assets/images/fourthLanding.png
  src/assets/images/secondLanding.png
  src/assets/images/thirdLanding.png
  src/components/Card/index.tsx
  src/components/Layout/components/Footer.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/constants/icon.ts
  src/domain/landing/components/LandingCard.tsx
  src/domain/landing/constants/index.ts
  src/domain/landing/index.tsx
  src/domain/landing/style.css.ts
  src/styles/font.ts
Labels: feature

#77 [Feature/Bar-247] 랜딩 페이지 CSS 수정
  src/components/Layout/components/Footer.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.css.ts
  src/domain/landing/index.tsx
  src/domain/landing/style.css.ts
Labels: feature

#76 [Feature/BAR-244] 끄적이는 페이지 메모 작성시 하단으로 스크롤 이동 및 툴팁 적용
  pages/main/index.tsx
  src/components/Button/components/TooltipButton/index.tsx
  src/components/Button/components/TooltipButton/style.css.ts
  src/components/Card/style.css.ts
  src/components/Dropdown/FolderDropdown/index.tsx
  src/components/Dropdown/FolderDropdown/style.css.ts
  src/components/Dropdown/MenuDropdown/index.tsx
  src/components/Dropdown/style.css.ts
  src/components/Tooltip/style.css.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/History/style.css.ts
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Card/Today/style.css.ts
  src/domain/끄적이는/components/Today/components/SpellCheckCard/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckCard/style.css.ts
  src/domain/끄적이는/queries/useGetHistory.ts
  src/domain/끄적이는/style.css.ts
  src/domain/저장하는/components/ArchiveFolder/index.tsx
  src/domain/저장하는/components/ArchiveFolder/style.css.ts
  src/domain/저장하는/components/ArchivedCard/index.tsx
  src/domain/저장하는/components/Folder/style.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/hooks/usePosition.ts
  src/styles/global.css.ts
Labels: feature

#78 [Fix/BAR-248] 로그인 이슈 해결
  middleware.ts
  src/assets/images/fifthLanding.png
  src/assets/images/fifthLanding.svg
  src/assets/images/fourthLanding.png
  src/assets/images/fourthLanding.svg
  src/assets/images/secondLanding.png
  src/assets/images/secondLanding.svg
  src/assets/images/thirdLanding.png
  src/assets/images/thirdLanding.svg
  src/components/Layout/components/Header.tsx
  src/components/Layout/index.tsx
  src/domain/landing/index.tsx
  src/domain/landing/style.css.ts
  src/models/layout.ts
Labels: fix

#79 [Fix/BAR-250] 폴더 삭제 에러 해결
  src/api/http.ts
  src/api/memoFolder/index.ts
  src/api/memoFolder/mutations/useDeleteMemoFolder.ts
  src/api/memoFolder/mutations/useUpdateMemoFolder.ts
  src/components/Button/components/TooltipButton/index.tsx
  src/components/Card/index.tsx
  src/components/Dropdown/FolderDropdown/index.tsx
  src/components/Dropdown/MenuDropdown/index.tsx
  src/components/Dropdown/components/DropdownItem.tsx
  src/components/Dropdown/index.tsx
  src/components/Modal/modals/MakeFolder.tsx
  src/components/Modal/style.css.ts
  src/constants/spellCheck.ts
  src/constants/toast.ts
  src/domain/landing/components/LandingCard.tsx
  src/domain/landing/style.css.ts
  src/domain/끄적이는/components/Card/History/index.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Today/components/SpellCheckCard/index.tsx
  src/domain/끄적이는/mutations/useSaveTemporalMemo.ts
  src/domain/저장하는/components/ArchiveFolder/index.tsx
  src/domain/저장하는/components/ArchiveFolder/style.css.ts
  src/domain/저장하는/components/ArchivedCard/index.tsx
  src/domain/저장하는/components/ArchivedCard/style.css.ts
  src/domain/저장하는/components/DeleteFolderModal/index.tsx
  src/domain/저장하는/components/Folder/style.css.ts
  src/domain/저장하는/mutations/useDeleteArchives.ts
  src/domain/참고하는/components/참고하는TemplateCard.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.tsx
  src/domain/참고하는/queries/useCopyTemplate.ts
  src/domain/참고하는/queries/useSaveTemplate.ts
  src/domain/참고하는/utils/index.ts
  src/hooks/useDisclosure.ts
  src/queries/usePostSpellCheck.ts
Labels: fix

#81 [Fix/BAR-253] 랜딩 페이지 svg 아이콘 미반영 푸터 위치 문제 해결
  src/assets/images/fifthLanding.svg
  src/assets/images/fourthLanding.svg
  src/components/Layout/components/Footer.tsx
  src/components/Layout/style.css.ts
  src/domain/landing/index.tsx
  src/domain/landing/style.css.ts
Labels: fix

#80 [Fix/BAR-252] 메인 페이지의 type searchParam에 저장
  middleware.ts
  pages/main/index.tsx
  pages/redirect/[authType]/index.tsx
  src/components/Layout/MainPageTab.tsx
  src/components/Layout/components/Header.tsx
  src/domain/저장하는/components/NotFoundArchiveCard/index.tsx
Labels: fix

#83 [Feature/BAR-255] 메모가 없는 경우, 끄적이는 페이지 안내 메시지 노출
  pages/main/index.tsx
  src/assets/icons/smileFace.svg
  src/assets/images/message.svg
  src/components/DayMessage/index.tsx
  src/components/DayMessage/style.css.ts
  src/components/Dropdown/FolderDropdown/index.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Guide/index.tsx
  src/domain/끄적이는/components/Guide/style.css.ts
  src/domain/끄적이는/components/History/index.css.ts
  src/domain/끄적이는/components/History/index.tsx
  src/domain/끄적이는/components/Today/index.css.ts
  src/domain/끄적이는/components/Today/index.tsx
  src/domain/끄적이는/components/WriteTabContent/index.tsx
  src/domain/끄적이는/components/WriteTabContent/style.css.ts
  src/domain/끄적이는/mutations/useDeleteTemporalMemo.ts
  src/domain/끄적이는/mutations/useEditTemporalMemo.ts
  src/domain/끄적이는/mutations/useSaveTemporalMemo.ts
  src/domain/끄적이는/queries/useGetHistory.ts
  src/domain/저장하는/mutations/useUpdateArchives.ts
Labels: feature

#84 [Fix/BAR-259] 특수문자가 포함된 문장의 맞춤법 검사 오류 해결
  pages/api/spell-check.ts
Labels: fix, 끄적이는

#87 [Fix/BAR-264] 끄적이는 스크롤 이슈 해결
  src/components/Card/style.css.ts
  src/components/Dropdown/style.css.ts
  src/components/Input/WriteInput/index.tsx
  src/components/Input/WriteInput/style.css.ts
  src/components/Layout/MainPageTab.tsx
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/components/Card/Today/style.css.ts
  src/domain/끄적이는/components/Today/index.css.ts
  src/domain/끄적이는/components/Today/index.tsx
  src/domain/끄적이는/components/WriteTabContent/index.tsx
  src/domain/끄적이는/components/WriteTabContent/style.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.css.ts
  src/domain/참고하는/components/참고하는TemplateCard.tsx
Labels: fix

#86 [Fix/BAR-260] EditInput 초기 rows 값 수정
  src/components/Card/style.css.ts
  src/components/Modal/modals/EditFolder.tsx
  src/components/Modal/modals/MakeFolder.tsx
  src/components/Modal/style.css.ts
  src/components/Tooltip/style.css.ts
  src/domain/landing/style.css.ts
  src/domain/끄적이는/components/EditInput.tsx
  src/domain/끄적이는/components/editInput.css.ts
Labels: fix, 저장하는

#89 [Fix/BAR-269] 끄적이는 페이지 아카이빙 제거
  src/components/Dropdown/FolderDropdown/index.tsx
  src/components/Dropdown/FolderDropdown/style.css.ts
  src/domain/끄적이는/components/Card/Today/index.tsx
  src/domain/끄적이는/mutations/useDeleteArchive.ts
Labels: fix

#90 [Fix/BAR-270] 계정설정 페이지 연동
  pages/main/index.tsx
  pages/profile/index.tsx
  src/api/http.ts
  src/domain/계정설정/components/ExitModal/index.tsx
  src/domain/계정설정/components/Form/index.tsx
  src/domain/계정설정/mutations/useExitAccount.ts
  src/domain/계정설정/queries/useGetProfile.ts
Labels: fix
